version: "3"
services:
  web:
    image: energy-service
    deploy:
      replicas: 5
      # resources:
        # limits:
        #   cpus: "0.1"
        #   memory: 5000M
      restart_policy:
        condition: on-failure
    ports:
      - "8789:8789"
    networks:
      - webnet

  influx:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - "/var/lib/docker/volumes/energydb/_data:/var/lib/influxdb"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

  # visualizer:
  #   image: dockersamples/visualizer:stable
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   deploy:
  #     placement:
  #       constraints: [node.role == manager]
  #   networks:
  #     - webnet
  
networks:
  webnet:
